pipeline:
  functional:
    deploy-integrate:
      - validate: deploy-production
      - integrate
edges:
  - integrate: deploy-production


hooks:
  pre_setup: bin/pre_setup

tool_config:
  git:
    version: 1.8.5.5

phantomjs:
  version: '1.9.7'

ruby:
  ruby_version: "2.3.1"

nodejs:
  version: '6.2.1'

java:
  java_version: java-8-openjdk
  maven_version: '3.3.9'

environment:
  HELLOWORLD_APP_NAME: "u252jm-Predix-HelloWorld-WebApp"

profiles:
  validate:
    test_exclude_pattern:
      - spec/**_spec.rb
    tests:
      - python scripts/installRefApp.py -i "${PREDIX_PREFIX:-$USER}jm" --only=validate

  functional:
    hooks:
      pre_setup: |
        set -e
        bin/pre_setup
        cd rmd-ref-app-ui
        export PATH=$PATH:`pwd`/node_modules/.bin/
        npm install
        npm install bower
        npm install grunt-cli
        bower install
    test_exclude_pattern:
      - spec/**_spec.rb
    tests:
      - type: junit
        command: cd dataingestion-service && mvn test
        report_files:
          - "dataingestion-service/target/*-reports/*.xml"
      - type: junit
        command: cd data-seed-service && mvn test
        report_files:
          - "data-seed-service/target/*-reports/*.xml"
      - type: junit
        command: cd machinedata-simulator && mvn verify
        report_files:
          - "machinedata-simulator/target/*-reports/*.xml"
      - type: junit
        command: cd predix-websocket-server && mvn verify
        report_files:
          - "predix-websocket-server/target/*-reports/*.xml"
      - type: junit
        command: cd rmd-datasource && mvn test
        report_files:
          - "rmd-datasource/target/*-reports/*.xml"
      - cd rmd-ref-app-ui && npm test || exit 0

  deploy-integrate:
    hooks:
      pre_setup: |
        set -e
        export PATH=$PATH:`pwd`/node_modules/.bin/
        bin/pre_setup
        npm install bower
        npm install grunt-cli
    test_exclude_pattern:
      - spec/**_spec.rb
    tests:
      - PATH=$PATH:`pwd`/node_modules/.bin/ python scripts/installRefApp.py -i "${PREDIX_PREFIX:-$USER}jm"

  integrate:
    hooks:
      pre_setup: |
        bin/pre_setup
        gem install java-properties
        bin/generate_properties
    tests:
      - type: junit
        command: cd rmd-datasource && mvn verify
        report_files:
          - "rmd-datasource/target/*-reports/*.xml"
      - CF_UI_PREFIX=${PREDIX_PREFIX:-$USER}jm bundle exec rspec spec/predix_rmd_ref_app_spec.rb
    test_exclude_pattern:
      - spec/**_spec.rb
    environment:
      BROWSER: chrome
      CONFIRM_POP_UP: true

  deploy-production:
    hooks:
      pre_setup: |
        set -e
        export PATH=$PATH:`pwd`/node_modules/.bin/
        bin/pre_setup
        npm install bower
        npm install grunt-cli
    test_exclude_pattern:
      - spec/**_spec.rb
    tests:
      - PATH=$PATH:`pwd`/node_modules/.bin/ python scripts/installRefApp.py -i ${PREDIX_PREFIX:-production}

